### ISSUE TITLE
Ubuntu20.04启动时出现报错

### ISSUE THREAD

**Issue by daqyt** [CikeyQi/nsfwjs-plugin#21]
启动时日志如下
``node
[10:08:17.272][ERRO] 载入插件错误：[31mExamine[39m
[10:08:17.273][ERRO] Error: libtensorflow.so.2: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1472:18)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/bot/bot/jqr/TRSS-Yunzai/node_modules/.pnpm/@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[10:08:17.275][ERRO] 载入插件错误：[31mListen[39m
[10:08:17.275][ERRO] Error: libtensorflow.so.2: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1472:18)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/bot/bot/jqr/TRSS-Yunzai/node_modules/.pnpm/@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[10:08:17.277][MARK] Error: libtensorflow.so.2: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1472:18)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/bot/bot/jqr/TRSS-Yunzai/node_modules/.pnpm/@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12) {
  code: 'ERR_DLOPEN_FAILED'
} Promise {
  <rejected> Error: libtensorflow.so.2: cannot open shared object file: No such file or directory
      at Module._extensions..node (node:internal/modules/cjs/loader:1472:18)
      at Module.load (node:internal/modules/cjs/loader:1206:32)
      at Module._load (node:internal/modules/cjs/loader:1022:12)
      at Module.require (node:internal/modules/cjs/loader:1234:19)
      at require (node:internal/modules/helpers:176:18)
      at Object.<anonymous> (/bot/bot/jqr/TRSS-Yunzai/node_modules/.pnpm/@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
      at Module._compile (node:internal/modules/cjs/loader:1375:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
      at Module.load (node:internal/modules/cjs/loader:1206:32)
      at Module._load (node:internal/modules/cjs/loader:1022:12) {
    code: 'ERR_DLOPEN_FAILED'
  }
}
[10:08:17.576][MARK] [Handler][Reg]: [ws-plugin-tool][ws.tool.toImg]
``

**Comment by CikeyQi** [comment]
参考：https://github.com/tensorflow/tfjs/issues/3287
