### ISSUE TITLE
出现#8号issue的情况并且找不到tfjs_binding.node

### ISSUE THREAD

**Issue by Conkinya** [CikeyQi/nsfwjs-plugin#25]
详情见https://github.com/CikeyQi/nsfwjs-plugin/issues/8
**确认给出的路径没有tfjs_binding.node，确定整个yunzai文件夹里都找不到tfjs_binding.node**，已经按照https://github.com/CikeyQi/nsfwjs-plugin?tab=readme-ov-file#%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6 给出的方法多次安装、重启
![ed5fcf2b1bb93d380e5637542b2effc7](https://github.com/CikeyQi/nsfwjs-plugin/assets/95989221/a7cedf2b-c499-403c-8119-41c1f1f2b37a)
![4f1c59a539afdc101309bd75024df0c7](https://github.com/CikeyQi/nsfwjs-plugin/assets/95989221/8464ba65-02ce-4954-a4db-283b3bc27cb9)

**[TRSSYz][14:21:31.464][ERRO]** 载入插件错误：Examine
[TRSSYz][14:21:31.468][ERRO] Error: The Node.js native addon module (tfjs_binding.node) can not be f
ound at path: C:\msys64\home\Administrator\TRSS_AllBot\TRSS-Yunzai\node_modules\.pnpm\@tensorflow+tf
js-node@3.21.1_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the nati
ve addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/
blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (C:\msys64\home\Administrator\TRSS_AllBot\TRSS-Yunzai\node_modules\.pnpm\@
tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node\dist\index.js:49:11)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async Promise.allSettled (index 0)
**[TRSSYz][14:21:31.477][ERRO]** 载入插件错误：Listen
[TRSSYz][14:21:31.480][ERRO] Error: The Node.js native addon module (tfjs_binding.node) can not be f
ound at path: C:\msys64\home\Administrator\TRSS_AllBot\TRSS-Yunzai\node_modules\.pnpm\@tensorflow+tf
js-node@3.21.1_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the nati
ve addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/
blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (C:\msys64\home\Administrator\TRSS_AllBot\TRSS-Yunzai\node_modules\.pnpm\@
tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node\dist\index.js:49:11)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async Promise.allSettled (index 0)
**[TRSSYz][14:21:31.490][INFO] - NSFWJS-PLUGIN 载入成功**

**Comment by Conkinya** [comment]
是否需要提供安装依赖时的日志和硬件情况？

**Comment by Conkinya** [comment]
Administrator@WIN-20240321CIJ MINGW64 /c/msys64/home/Administrator/TRSS_AllBot/TRSS-Yunzai (main)
$ cd ./plugins/nsfwjs-plugin && pnpm install
Scope: all 8 workspace projects
../..                                    | Progress: resolved 1, reused 0, downloaded 0, added 0
../..                                    | Progress: resolved 12, reused 5, downloaded 0, added 0
../miao-plugin                           |  WARN  deprecated request@2.88.2
../..                                    | Progress: resolved 19, reused 14, downloaded 0, added 0
../..                                    | Progress: resolved 30, reused 25, downloaded 0, added 0
../..                                    | Progress: resolved 31, reused 26, downloaded 0, added 0
../..                                    | Progress: resolved 38, reused 33, downloaded 0, added 0
../..                                    | Progress: resolved 41, reused 37, downloaded 0, added 0
../..                                    | Progress: resolved 84, reused 41, downloaded 0, added 0
../..                                    | Progress: resolved 161, reused 51, downloaded 0, added 0
../..                                    | Progress: resolved 227, reused 60, downloaded 0, added 0
../..                                    | Progress: resolved 274, reused 83, downloaded 0, added 0
../..                                    | Progress: resolved 306, reused 114, downloaded 0, added 0
../..                                    | Progress: resolved 314, reused 142, downloaded 0, added 0
../..                                    | Progress: resolved 338, reused 170, downloaded 0, added 0
../..                                    | Progress: resolved 363, reused 198, downloaded 0, added 0
../..                                    | Progress: resolved 385, reused 218, downloaded 0, added 0
../..                                    | Progress: resolved 398, reused 232, downloaded 0, added 0
../..                                    | Progress: resolved 414, reused 247, downloaded 0, added 0
../..                                    | Progress: resolved 419, reused 251, downloaded 0, added 0
../..                                    | Progress: resolved 439, reused 272, downloaded 0, added 0
../..                                    | Progress: resolved 439, reused 276, downloaded 0, added 0
../..                                    | Progress: resolved 439, reused 286, downloaded 0, added 0
../..                                    | Progress: resolved 439, reused 312, downloaded 0, added 0
../..                                    | Progress: resolved 439, reused 331, downloaded 0, added 0
../..                                    | Progress: resolved 439, reused 344, downloaded 0, added 0
../..                                    | Progress: resolved 439, reused 345, downloaded 0, added 0
../..                                    | Progress: resolved 439, reused 375, downloaded 0, added 0
../..                                    | Progress: resolved 439, reused 402, downloaded 0, added 0
../..                                    | Progress: resolved 439, reused 416, downloaded 0, added 0
../..                                    | Progress: resolved 449, reused 437, downloaded 0, added 0
../..                                    | Progress: resolved 468, reused 456, downloaded 0, added 0
../..                                    | Progress: resolved 482, reused 470, downloaded 0, added 0
../..                                    | Progress: resolved 492, reused 481, downloaded 0, added 0
../..                                    | Progress: resolved 510, reused 499, downloaded 0, added 0
../..                                    | Progress: resolved 531, reused 522, downloaded 0, added 0
../..                                    | Progress: resolved 542, reused 532, downloaded 0, added 0
../..                                    | Progress: resolved 562, reused 554, downloaded 0, added 0
../..                                    | Progress: resolved 583, reused 573, downloaded 0, added 0
../..                                    | Progress: resolved 604, reused 595, downloaded 0, added 0
../..                                    | Progress: resolved 631, reused 622, downloaded 0, added 0
../..                                    | Progress: resolved 645, reused 635, downloaded 0, added 0
../..                                    | Progress: resolved 676, reused 671, downloaded 0, added 0
../..                                    | Progress: resolved 700, reused 698, downloaded 0, added 0
../..                                    | Progress: resolved 736, reused 733, downloaded 0, added 0
../..                                    | Progress: resolved 765, reused 761, downloaded 0, added 0
 WARN  3 deprecated subdependencies found: @npmcli/move-file@1.1.2, har-validator@5.1.5, uuid@3.4.0
../..                                    | Progress: resolved 766, reused 763, downloaded 0, added 0
../..                                    | +765 ++++++++++++++++++++++++++++++++
../..                                    | Progress: resolved 766, reused 765, downloaded 0, added 0
../..                                    | Progress: resolved 766, reused 765, downloaded 0, added 0, done
.../node_modules/@tensorflow/tfjs-node install$ node scripts/install.js
.../node_modules/@tensorflow/tfjs-node install: CPU-windows-3.21.1.zip
.../node_modules/@tensorflow/tfjs-node install: * Building TensorFlow Node.js bindings
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp info it worked if it ends with ok
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp info using node-pre-gyp@1.0.9
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp info using node@20.12.0 | win32 | x64
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp info check checked for "C:\msys64\home\Administrator\TRSS_AllBot\TRSS-Yunzai\node_modules\.pnpm\@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node" (not found)
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/3.21.1/CPU-windows-3.21.1.zip
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/3.21.1/CPU-windows-3.21.1.zip
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@3.21.1 and node@20.12.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp)
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v8/3.21.1/CPU-windows-3.21.1.zip
.../node_modules/@tensorflow/tfjs-node install: gyp info it worked if it ends with ok
.../node_modules/@tensorflow/tfjs-node install: gyp info using node-gyp@9.4.1
.../node_modules/@tensorflow/tfjs-node install: gyp info using node@20.12.0 | win32 | x64
.../node_modules/@tensorflow/tfjs-node install: gyp info ok
.../node_modules/@tensorflow/tfjs-node install: gyp info it worked if it ends with ok
.../node_modules/@tensorflow/tfjs-node install: gyp info using node-gyp@9.4.1
.../node_modules/@tensorflow/tfjs-node install: gyp info using node@20.12.0 | win32 | x64
.../node_modules/@tensorflow/tfjs-node install: gyp info find Python using Python version 3.12.2 found at "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe"
.../node_modules/@tensorflow/tfjs-node install: gyp http GET https://nodejs.org/download/release/v20.12.0/node-v20.12.0-headers.tar.gz
.../node_modules/@tensorflow/tfjs-node install: gyp http 200 https://nodejs.org/download/release/v20.12.0/node-v20.12.0-headers.tar.gz
.../node_modules/@tensorflow/tfjs-node install: gyp http GET https://nodejs.org/download/release/v20.12.0/SHASUMS256.txt
.../node_modules/@tensorflow/tfjs-node install: gyp http GET https://nodejs.org/download/release/v20.12.0/win-x64/node.lib
.../node_modules/@tensorflow/tfjs-node install: gyp http 200 https://nodejs.org/download/release/v20.12.0/SHASUMS256.txt
.../node_modules/@tensorflow/tfjs-node install: gyp http 200 https://nodejs.org/download/release/v20.12.0/win-x64/node.lib
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS msvs_version not set from command line or npm config
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS **************************************************************
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS You need to install the latest version of Visual Studio
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS including the "Desktop development with C++" workload.
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS For more information consult the documentation at:
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS **************************************************************
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! find VS
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! configure error
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack Error: Could not find any Visual Studio installation to use
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:75:16
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:380:14)
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:71:14
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack     at VisualStudioFinder.findVisualStudio2015 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:364:14)
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:67:12
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack     at failPowershell (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:156:7)
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack     at VisualStudioFinder.parseData (C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:170:14)
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:143:14
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! stack     at ChildProcess.exithandler (node:child_process:414:7)
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! System Windows_NT 10.0.19044
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\msys64\\home\\Administrator\\TRSS_AllBot\\TRSS-Yunzai\\node_modules\\.pnpm\\@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\\msys64\\home\\Administrator\\TRSS_AllBot\\TRSS-Yunzai\\node_modules\\.pnpm\\@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v8" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! cwd C:\msys64\home\Administrator\TRSS_AllBot\TRSS-Yunzai\node_modules\.pnpm\@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! node -v v20.12.0
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! node-gyp -v v9.4.1
.../node_modules/@tensorflow/tfjs-node install: gyp ERR! not ok
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! build error
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\msys64\home\Administrator\TRSS_AllBot\TRSS-Yunzai\node_modules\.pnpm\@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\msys64\home\Administrator\TRSS_AllBot\TRSS-Yunzai\node_modules\.pnpm\@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node\lib\napi-v8 --napi_version=9 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\msys64\home\Administrator\TRSS_AllBot\TRSS-Yunzai\node_modules\.pnpm\@mapbox+node-pre-gyp@1.0.9\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! System Windows_NT 10.0.19044
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\msys64\\home\\Administrator\\TRSS_AllBot\\TRSS-Yunzai\\node_modules\\.pnpm\\@mapbox+node-pre-gyp@1.0.9\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! cwd C:\msys64\home\Administrator\TRSS_AllBot\TRSS-Yunzai\node_modules\.pnpm\@tensorflow+tfjs-node@3.21.1_seedrandom@3.0.5\node_modules\@tensorflow\tfjs-node
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! node -v v20.12.0
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! node-pre-gyp -v v1.0.9
.../node_modules/@tensorflow/tfjs-node install: node-pre-gyp ERR! not ok
.../node_modules/@tensorflow/tfjs-node install: Failed
 ELIFECYCLE  Command failed with exit code 1.
