### ISSUE TITLE
检测到违规图后报错

### ISSUE THREAD

**Issue by ElaineOwO** [CikeyQi/nsfwjs-plugin#26]
```
[TRSSYz][02:10:48.140][ERRO] [NSFWJS-监听][Listen]
[TRSSYz][02:10:48.141][ERRO] AxiosError: Request failed with status code 404
    at settle (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/node_modules/.pnpm/axios@1.4.0/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/node_modules/.pnpm/axios@1.4.0/node_modules/axios/lib/adapters/http.js:570:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
但貌似功能都正常，好奇怪

NTQQ版本9.9.9-22868
liteloaderQQNT版本1.1.1
llonebot版本3.22.1
trss-yunzai版本3.1.3

**Comment by CikeyQi** [comment]
无法获取从图片地址获取到图片
